<?php

return [
    [
        'key'        => 'dashboard',
        'name'       => 'admin::app.layouts.dashboard',
        'route'      => 'admin.dashboard.index',
        'sort'       => 1,
        'icon-class' => 'fal fa-tachometer-alt-fast',
    ], [
        'key'        => 'sales',
        'name'       => 'admin::app.layouts.sales',
        'route'      => 'admin.sales.orders.index',
        'sort'       => 2,
        'icon-class' => 'fal fa-file-chart-line',
    ], [
        'key'        => 'sales.orders',
        'name'       => 'admin::app.layouts.orders',
        'route'      => 'admin.sales.orders.index',
        'sort'       => 1,
        'icon-class' => '',
    ]/*,
        [
        'key' => 'sales.preorder',
        'name' => 'preorder::app.admin.layouts.preorder',
        'route' => 'admin.preorder.preorders.index',
        'sort' => 3,
        'icon-class' => 'preorder-icon',
    ]*/
    , [
        'key'        => 'sales.shipments',
        'name'       => 'admin::app.layouts.shipments',
        'route'      => 'admin.sales.shipments.index',
        'sort'       => 3,
        'icon-class' => '',
    ], [
        'key'        => 'sales.invoices',
        'name'       => 'admin::app.layouts.invoices',
        'route'      => 'admin.sales.invoices.index',
        'sort'       => 4,
        'icon-class' => '',
    ], [
        'key'        => 'sales.refunds',
        'name'       => 'admin::app.layouts.refunds',
        'route'      => 'admin.sales.refunds.index',
        'sort'       => 5,
        'icon-class' => '',
    ], [
        'key'        => 'catalog',
        'name'       => 'admin::app.layouts.catalog',
        'route'      => 'admin.catalog.products.index',
        'sort'       => 3,
        'icon-class' => 'fal fa-clipboard-list-check',
    ], [
        'key'        => 'catalog.products',
        'name'       => 'admin::app.layouts.products',
        'route'      => 'admin.catalog.products.index',
        'sort'       => 1,
        'icon-class' => '',
    ], [
        'key'        => 'catalog.families',
        'name'       => 'admin::app.layouts.attribute-families',
        'route'      => 'admin.catalog.families.index',
        'sort'       => 2,
        'icon-class' => '',
    ], [
        'key'        => 'catalog.attributes',
        'name'       => 'admin::app.layouts.attributes',
        'route'      => 'admin.catalog.attributes.index',
        'sort'       => 3,
        'icon-class' => '',
    ], [
        'key'        => 'catalog.categories',
        'name'       => 'admin::app.layouts.categories',
        'route'      => 'admin.catalog.categories.index',
        'sort'       => 4,
        'icon-class' => '',
    ], [
        'key'        => 'customers',
        'name'       => 'admin::app.layouts.customers',
        'route'      => 'admin.customer.index',
        'sort'       => 4,
        'icon-class' => 'fal fa-users',
    ], [
        'key'        => 'customers.customers',
        'name'       => 'admin::app.layouts.customers',
        'route'      => 'admin.customer.index',
        'sort'       => 1,
        'icon-class' => '',
    ], [
        'key'        => 'customers.groups',
        'name'       => 'admin::app.layouts.groups',
        'route'      => 'admin.groups.index',
        'sort'       => 2,
        'icon-class' => '',
    ], [
        'key'        => 'customers.reviews',
        'name'       => 'admin::app.layouts.reviews',
        'route'      => 'admin.customer.review.index',
        'sort'       => 3,
        'icon-class' => '',
    ], [
        'key'        => 'customers.subscribers',
        'name'       => 'admin::app.layouts.newsletter-subscriptions',
        'route'      => 'admin.customers.subscribers.index',
        'sort'       => 4,
        'icon-class' => '',
        ] , [
        'key'        => 'settings',
        'name'       => 'admin::app.layouts.settings',
        'route'      => 'company.profile.index',
        'sort'       => 6,
        'icon-class' => 'fal fa-cog',
    ],
// removed because of restructuring menu - task № 29454368,
// now settings and configuration menu builds in "custom-nav-aside.blade.php" and "custom-tabs.blade.php"
//    [    'key'        => 'settings.general',
//        'name'       => 'admin::app.layouts.general',
//        'route'      => 'company.profile.index',
//        'sort'       => 1,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.general.profile',
//        'name'       => 'admin::app.layouts.profile',
//        'route'      => 'company.profile.index',
//        'sort'       => 1,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.general.address',
//        'name'       => 'admin::app.layouts.address',
//        'route'      => 'company.address.index',
//        'sort'       => 2,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.general.logo',
//        'name'       => 'admin::app.layouts.logo',
//        'route'      => 'admin.configuration.index',
//        'sort'       => 3,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.general.add_custom_code',
//        'name'       => 'admin::app.layouts.add_custom_code',
//        'route'      => 'admin.configuration.index',
//        'sort'       => 4,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.regional_settings',
//        'name'       => 'admin::app.layouts.regional_settings',
//        'route'      => 'admin.locales.index',
//        'sort'       => 2,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.regional_settings.locales',
//        'name'       => 'admin::app.layouts.locales',
//        'route'      => 'admin.locales.index',
//        'sort'       => 1,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.regional_settings.currencies',
//        'name'       => 'admin::app.layouts.currencies',
//        'route'      => 'admin.currencies.index',
//        'sort'       => 2,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.regional_settings.exchange_rates',
//        'name'       => 'admin::app.layouts.exchange-rates',
//        'route'      => 'admin.exchange_rates.index',
//        'sort'       => 3,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.inventory_sources',
//        'name'       => 'admin::app.layouts.inventory-sources',
//        'route'      => 'admin.inventory_sources.index',
//        'sort'       => 4,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.channels',
//        'name'       => 'admin::app.layouts.channels',
//        'route'      => 'admin.channels.index',
//        'sort'       => 5,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.users',
//        'name'       => 'admin::app.layouts.users',
//        'route'      => 'admin.users.index',
//        'sort'       => 6,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.users.users',
//        'name'       => 'admin::app.layouts.users',
//        'route'      => 'admin.users.index',
//        'sort'       => 1,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.users.roles',
//        'name'       => 'admin::app.layouts.roles',
//        'route'      => 'admin.roles.index',
//        'sort'       => 2,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.sliders',
//        'name'       => 'admin::app.layouts.sliders',
//        'route'      => 'admin.sliders.index',
//        'sort'       => 7,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.taxes',
//        'name'       => 'admin::app.layouts.taxes',
//        'route'      => 'admin.tax-categories.index',
//        'sort'       => 8,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.taxes.tax-categories',
//        'name'       => 'admin::app.layouts.tax-categories',
//        'route'      => 'admin.tax-categories.index',
//        'sort'       => 1,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.taxes.tax-rates',
//        'name'       => 'admin::app.layouts.tax-rates',
//        'route'      => 'admin.tax-rates.index',
//        'sort'       => 2,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.company',
//        'name'       => 'saas::app.admin.tenant.company-profile',
//        'route'      => 'company.profile.index',
//        'sort'       => 9,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.company.profile',
//        'name'       => 'saas::app.admin.tenant.profile',
//        'route'      => 'company.profile.index',
//        'sort'       => 1,
//        'icon-class' => '',
//    ], [
//        'key'        => 'settings.company.address',
//        'name'       => 'saas::app.admin.tenant.address-details',
//        'route'      => 'company.address.index',
//        'sort'       => 2,
//        'icon-class' => '',
//    ],
//    [
//        'key'        => 'settings.PWA',
//        'name'       => 'pwa::app.admin.layouts.push-notification',
//        'route'      => 'pwa.pushnotification.create',
//        'sort'       => 9,
//        'icon-class' => 'pwa-icon',
//    ], [
//        'key'   => 'settings.PWA.index',
//        'route' => 'pwa.pushnotification.index',
//        'name'  => 'pwa::app.admin.layouts.push-notification',
//        'sort'  => 1,
//    ]

     [
        'key'        => 'promotions',
        'name'       => 'admin::app.layouts.promotions',
        'route'      => 'admin.catalog-rules.index',
        'sort'       => 5,
        'icon-class' => 'fal fa-badge-percent',
    ], [
        'key'        => 'promotions.catalog-rules',
        'name'       => 'admin::app.promotions.catalog-rules.title',
        'route'      => 'admin.catalog-rules.index',
        'sort'       => 1,
        'icon-class' => '',
    ], [
        'key'        => 'promotions.cart-rules',
        'name'       => 'admin::app.promotions.cart-rules.title',
        'route'      => 'admin.cart-rules.index',
        'sort'       => 2,
        'icon-class' => '',
    ], [
        'key'        => 'cms',
        'name'       => 'admin::app.layouts.cms',
        'route'      => 'admin.cms.index',
        'sort'       => 5,
        'icon-class' => 'fal fa-browser',
    ], [
        'key'        => 'cms.pages',
        'name'       => 'admin::app.cms.pages.pages',
        'route'      => 'admin.cms.index',
        'sort'       => 1,
        'icon-class' => '',
    ],
    [
        'key'        => 'cms.meta-data',
        'name'       => 'velocity::app.admin.layouts.meta-data',
        'route'      => "admin.page_builder.edit",
        'params'     =>  ['route' => 'home'],
        'sort'       => 2,
        'icon-class' => '',
    ],
    [
        'key'        => 'cms.footer',
        'name'       => 'velocity::app.admin.layouts.footer',
        'route'      => "admin.page_builder.edit",
        'params'     =>  ['route' => 'footer'],
        'sort'       => 2,
        'icon-class' => '',
    ],
    [
        'key'        => 'cms.header',
        'name'       => 'velocity::app.admin.layouts.header-content',
        'route'      => 'velocity.admin.content.index',
        'sort'       => 4,
        'icon-class' => '',
    ]
];